FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt update && \
    apt install -y python3.9 python3.9-venv python3.9-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["python3.9"]