#cloud-config
users:
  - name: ${vm_user}
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys: ${jsonencode(ssh_public_key)}

package_update: true
package_upgrade: false
packages:
  - vim
  - nginx  # Устанавливаем Nginx

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
