#cloud-config
users:
  - name: roman
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh_authorized_keys: ${jsonencode(ssh_public_key)}

ssh_pwauth: false

package_update: true
package_upgrade: false
packages:
  - vim
  - nginx  # Устанавливаем Nginx

runcmd:
  - systemctl enable nginx 
  - systemctl start nginx
